version: ~> 1.0
os:
- linux
language: python
dist: bionic
env:
  global:
  - DEBUG="travis"
python:
- "3.6"
services:
- docker
branches:
  except:
  - gh-pages
before_install:
- chmod +x ./after-effects
- chmod +x ./tests/*.sh
- chmod  +x ./build/*.sh
before_deploy: source ./build/export-travis-tag-message.sh
jobs:
  allow_failures:
  - env: TEST_ENV="Ubuntu-Pre-Release-Docker"
  - env: TEST_ENV="Debian11-Docker"

  include:
  - stage: Shellcheck
    env: TEST_ENV="Shellcheck"
    script:
    - ./tests/test-shell-scripts.sh
    - ./tests/lint-dockerfiles.sh

  - stage: Test
    env: TEST_ENV="Eoan-Docker"
    script: ./tests/test-distro.sh "ubuntu" "eoan" "default.yml" "true"

  - env: TEST_ENV="Disco-Docker"
    script: ./tests/test-distro.sh "ubuntu" "disco"

  - env: TEST_ENV="Bionic-Docker"
    script: ./tests/test-distro.sh "ubuntu" "bionic"

  - env: TEST_ENV="Bionic-Host"
    script: ./tests/test-distro.sh "ubuntu" "host"

  - env: TEST_ENV="Bionic-Host-ARM64"
    script: ./tests/test-distro.sh "ubuntu" "host"
    arch: arm64

  - env: TEST_ENV="Xenial-Docker"
    script: ./tests/test-distro.sh "ubuntu" "xenial"

  - env: TEST_ENV="Debian9-Docker"
    script: ./tests/test-distro.sh "debian" "stretch"

  - env: TEST_ENV="Debian8-Docker"
    script: ./tests/test-distro.sh "debian" "jessie"

  - env: TEST_ENV="Debian10-Docker"
    script: ./tests/test-distro.sh "debian" "buster"

  - stage: Pre-Release-Builds
    env: TEST_ENV="Ubuntu-Pre-Release-Docker"
    script: ./tests/test-distro.sh "ubuntu" "focal" "pre-release.yml" "true"

  - env: TEST_ENV="Debian11-Docker"
    script: ./tests/test-distro.sh "debian" "bullseye" "pre-release.yml" "true"

  - stage: Documentation & Deploy
    env: TEST_ENV="Docs-Build"
    script:
      - "./build/build-docs.sh"
      - "cat ./_site/commit.json"
    deploy:
    - provider: pages
      deployment_file: false
      verbose: true
      local_dir: _site
      cleanup: false
      keep_history: true
      target_branch: gh-pages
      email: ${GITHUB_EMAIL}
      name: Valarie-CI-bot
      token: ${GITHUB_TOKEN}
      on:
        branch: master
    - provider: releases
      token: ${GITHUB_TOKEN}
      file:
      - after-effects
      - after-effects.asc
      - sha1sum.txt
      - sha256sum.txt
      - sha512sum.txt
      cleanup: false
      prerelease: true
      name: ${TRAVIS_TAG} - ${TRAVIS_TAG_MESSAGE}
      release_notes: "Please check the changelogs at https://ae.prasadt.com/changelogs/."
      overwrite: true
      on:
        branch: master
        tags: true
notifications:
  email: false
