version: "3"
services:
  site:
    command: serve --dev-addr=0.0.0.0:8000
    build:
      context: ./dockerfiles/mkdocs
      dockerfile: Dockerfile
    image: mkdocs-material:latest
#    image: squidfunk/mkdocs-material
    volumes:
      - $PWD:/srv
    ports:
      - 8000:8000
