version: "3"
services:
  site:
    command: serve --dev-addr=0.0.0.0:8000
    build:
      context: ./docs/
    image: mkdocs-material:latest
#    image: squidfunk/mkdocs-material
    volumes:
      - ./docs:/home/user/app/docs:ro
      - ./mkdocs.yml:/home/user/app/mkdocs.yml:ro
    ports:
      - 127.0.0.1:8000:8000
