
# Project information
site_name: Documentaion for After Effects
site_description: Effortless & Simple Ubuntu post-installation script
site_author: Prasad Tengse
site_url: https://ae.prasadt.com/
docs_dir: 'docs'
site_dir: '_site/'
# Repository
repo_name: ubuntu-post-install
repo_url: https://github.com/tprasadtp/ubuntu-post-install
edit_uri: "blob/version_checks_api/docs/"
remote_branch: gh-pages
remote_name: origin

# Copyright
copyright: 'Copyright &copy; 2018 Prasad Tengse'

# Configuration
theme:
  name: material
  tasks_dir: 'docs/theme-overrides/'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# tasksization
extra:
  social:
    - type: globe
      link: https://prasadt.com
    - type: github-alt
      link: https://github.com/tprasadtp
    - type: twitter
      link: https://twitter.com/tprasadtp
    - type: linkedin
      link: https://linkedin.com/in/prasadtengse

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
pages:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - FAQ:
    - Dependecies: faq/dependencies.md
    - Supported: faq/distros.md
    - Errors: faq/errors.md
    - Linux Mint: faq/linuxmint.md
    - Crashes: faq/crash.md
  - Command Line Options: clioptions.md
  - Logs: logs.md
  - CI & Testing: testing.md
  - Tasks:
    - Upgrade Packages: tasks/update.md
    - Add Repositories: tasks/addrepo.md
    - Install packages: tasks/apt.md
    - Add PPAs: tasks/ppa.md
    - Install Python packages: tasks/pip.md
    - Install Debian packages: tasks/deb.md
    - Pre-Post Hooks: tasks/hooks.md
    - Cleanup: tasks/cleanup.md
    - Delete log: tasks/log.md
  - Changelogs: changelogs.md
  - License & Privacy: license.md
  - More:
    - About: about/about.md
#    - Credits: about/credits.md
#    - Privacy: about/privacy-poclicy.md

# Google Analytics
google_analytics:
  - UA-101760811-5
  - auto
