
# Project information
site_name: Documentaion for After Effects
site_description: Effortless & Simple Ubuntu post-installation script
site_author: Prasad Tengse
site_url: https://ae.prasadt.com/
docs_dir: 'docs'
site_dir: '_site/'
# Repository
repo_name: ubuntu-post-install
repo_url: https://github.com/tprasadtp/ubuntu-post-install
edit_uri: "blob/master/docs/"
remote_branch: gh-pages
remote_name: origin

# Copyright
copyright: 'Copyright &copy; 2018 Prasad Tengse'

# Configuration
theme:
  name: material
  custom_dir: 'docs/theme-overrides/'

  # 404 page
  static_templates:
    - 404.html

  extra:
    manifest: 'manifest.webmanifest'

  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "book"

# tasksization
extra:
  social:
    - type: globe
      link: https://ae.prasadt.com
    - type: github-alt
      link: https://github.com/tprasadtp

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: tprasadtp
      repo: ubuntu-post-install

# Page tree
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - FAQ:
    - Dependecies: faq/dependencies.md
    - Distros: faq/distros.md
    - Errors & Issues: faq/errors.md
    - Linux Mint: faq/linuxmint.md
    - Others: faq/others.md
  - Options: clioptions.md
  - What can it do?: tasks.md
  - Configuration: configuration.md
  - Example Config YAML: yaml.md
  - Logs: logs.md
  - Testing: testing.md
  - News:
    - Changelog: changelogs.md
  - Other:
    - License: license.md
    - Privacy Policy: privacy.md

# Google Analytics
google_analytics:
  - UA-101760811-5
  - auto
