# Global settings applied to the whole site.
[build]
  publish = "_site/"

[build.environment]
  NOKOGIRI_USE_SYSTEM_LIBRARIES="true"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "chmod +x ./build/*.sh && ./build/netlify.sh --production"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  publish = "_site/"
  command = "chmod +x ./build/*.sh && ./build/netlify.sh --pull-request"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "chmod +x ./build/*.sh && ./build/netlify.sh --branch"

# Country specific rules
#[[redirects]]
#  from = "/"
#  to = "/unavailable"
#  status = 302
#  force = true
#  conditions = {Country = ["CN","HK","TW","CU","IR","PK","SD","SA","TR","RU","YE","BD"]}

# GH URLs
[[redirects]]
  from = "/git"
  to = "https://github.com/tprasadtp/ubuntu-post-install"
  status = 301
  force = true

[[redirects]]
  from = "/github"
  to = "https://github.com/tprasadtp/ubuntu-post-install"
  status = 301
  force = true

# Issues
[[redirects]]
  from = "/issue"
  query = {id = ":id"}
  to = "https://github.com/tprasadtp/ubuntu-post-install/issues/:id"
  status = 301
  force = true


[[redirects]]
  from = "/issues"
  to = "https://github.com/tprasadtp/ubuntu-post-install/issues"
  status = 301
  force = true

# Pulls
[[redirects]]
  from = "/pr"
  query = {id = ":id"}
  to = "https://github.com/tprasadtp/ubuntu-post-install/pull/:id"
  status = 301
  force = true


[[redirects]]
  from = "/prs"
  to = "https://github.com/tprasadtp/ubuntu-post-install/pulls"
  status = 301
  force = true

[[redirects]]
  from = "/dp"
  to = "/deploy.json"
  status = 301
  force = true

[[redirects]]
  from = "/commit"
  to = "/commit.json"
  status = 301
  force = true

# Version to old version.yml
# Avoid breaking old version checks
[[redirects]]
  from = "/config/version.yml"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/version.yml"
  status = 301
  force = true

# /version stuff
[[redirects]]
  from = "/version"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/version.yml"
  status = 301
  force = true


[[redirects]]
  from = "/sig/version"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/version.yml.asc"
  status = 301
  force = true

# /v2/version stuff
[[redirects]]
  from = "/v2/version"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/version.yml"
  status = 301
  force = true

[[redirects]]
  from = "/v2/sig/version"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/version.yml.asc"
  status = 301
  force = true

# Scripts
[[redirects]]
  from = "/get"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/after-effects"
  status = 301
  force = true

[[redirects]]
  from = "/sig/get"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/after-effects.asc"
  status = 301
  force = true

[[redirects]]
  from = "/sha256"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/sha256sum.txt"
  status = 301
  force = true

[[redirects]]
  from = "/sha512"
  to = "https://github.com/tprasadtp/ubuntu-post-install/releases/latest/download/sha512.txt"
  status = 301
  force = true
