# Global settings applied to the whole site.
[build]
  publish = "_site/"

[build.environment]
  NOKOGIRI_USE_SYSTEM_LIBRARIES="true"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "./vendor/netlify-build.sh --production"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  publish = "_site/"
  command = "./vendor/netlify-build.sh --pull-request"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "./vendor/netlify-build.sh --branch"
