# Install Config
api: 2
name: Minimal
author: Prasad T
# Configuration
config:
  # Enabled Tasks
  tasks:
    update: true
    upgrade: false
    # Add Repos
    # individual repos flags are mentioned under config.add_repo key
    repo: true
    # Add PPAs
    ppa: true
    # APT Packages
    apt: true
    # Whether to purge packages mentioned in config.purge key
    purge: true
    debs: true
    pip2: true
    pip3: true
    binaries: true
    snaps: false
  # Repository Flags
  add_repo:
    azurecli: true
    docker: true
    duo: true
    gcsfuse: true
    gvisor: true
    github: true
    google: true
    googlecloud: true
    hashicorp: true
    mendeley: false
    ros: true
    signal: true
    skype: true
    spotify: true
    vscode: true
    winehq: true

  # Flags
  flags:
    purge_enabled: true
    preserve_debs: false

  # Packages to purge
  purge:
    - gnome-mines
  # PPA
  ppa:
    - ppa:yubico/stable
  # Install components
  # APT Packages, Python Modules, Debian packages
  install:
    # Debian packages.deb files
    # CSV format
    debian_packages:
      - https://github.com/sharkdp/bat/releases/download/v0.16.0/bat-musl_0.16.0_amd64.deb,bat.deb
    binaries:
      - https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubectl,kubectl
    snaps:
      normal:
        - htop
      classic:
        - hugo
    python2:
      - aws
    python3:
      - coloredlogs
    apt:
      # Admin related Stuff
      administration:
        - curl
      # Security Related Stuff
      security:
        - gnupg2
      # Productivity & Office Tools.
      productivity:
        - curl
      # Tools related to development.
      development:
        - iputils-ping
      # Everything Else
      other:
        - less
      external:
        - gh
        - runsc
        - terraform
        - azure-cli
        - google-cloud-sdk
