# Version Config
api: 2
# Configuraion
version:
  number: 551
  name: 5.5.1-Beta
  changelog: 19.10, ElementaryOS 5.1 Support
# Stats reporting
stats:
  report: false
  node: https://stats.ae.prasadt.com/report
