# Version Config
api: 2
# Configuraion
version:
  number: 532
  name: 5.3.2
  changelog: Cosmic is now stable + Prep for Disco
# Stats reporting
stats:
  report: true
  node: https://stats.ae.prasadt.com/report
