style: github
template: CHANGELOG.md.tpl
info:
  title: CHANGELOG
  repository_url: https://github.com/tprasadtp/ubuntu-post-install
options:
  commits:
    filters:
      Type:
        - distro
        - feat
        - fix
        - perf
        - docs
        - refactor
        - ci
        - chore
  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - distro
      - feat
      - fix
      - perf
      - docs
      - refactor
      - ci
      - chore
    title_maps:
      distro: "🍧 Distro updates"
      feat: "🍒 Features & Enhancements"
      fix: "🐛 Bug Fixes"
      perf: "🚀 Performance Improvements"
      docs: "📖 Documentation"
      refactor: "☀️ Code Refactoring"
      chore: "🥺 Maintanance"
      ci: "🤖 Continuous Integration & Automation"
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGES
      - SECURITY UPDATES
      - CVE
      - FIXES

  issues:
    prefix:
      - "#"
      - GH-
      - GITHUB-

  refs:
    actions:
      - Closes
      - Fixes
      - Resolves

  merges:
    pattern: "^Merge branch '(\\w+)'$"
    pattern_maps:
      - Source

  reverts:
    pattern: "^Revert \"([\\s\\S]*)\"$"
    pattern_maps:
      - Header
