name: docs
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "netlify.toml"
      - "mkdocs.yml"
      - "runtime.txt"
      - "docker-compose.yml"
    tags-ignore:
      - "**"
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Deps
        run: |
          sudo apt-get update || true
          sudo apt-get install python3-pip python3-setuptools

      - name: Build Docs
        run: |
          ./build/docs.sh
          cat ./_site/commit.json

      # Git Settings
      - name: Setup Git
        run: |
          echo "Setting git conf user.email"
          git config --global user.email "valarie-ci-bot@users.noreply.github.com" && echo "Done"
          echo "Setting git conf user.name"
          git config --global user.name "valarie-ci-bot" && echo "Done"

      # Get Current gh-pages
      - name: Clone gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages
          fetch-depth: 0
      - name: Copy _site folder to pages
        run: |
          rsync -avh --ignore-times --delete --exclude '**/.git/**/*' --exclude '**/.git/' ./_site/ pages/
      - name: Commit Pages Built
        run: |
          cd pages
          git add --all
          git commit -s -m "Pages deploy ${GITHUB_SHA:0:7} BUILD-${GITHUB_RUN_NUMBER}"
      # Upload site data and checksums to artifacts
      - name: Artifacts _site
        uses: actions/upload-artifact@v1
        with:
          name: pages
          path: pages
